language: node_js
node_js:
  - "node"
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true