#!/bin/bash
shopt -s extglob

for file in !(README).md; do
  pandoc $file \
    --output="${file/.md/.html}" \
    --to=html5 \
    --css=tufte.css \
    --highlight-style=espresso \
    --standalone
done

pandoc --output=common-lisp-by-example.epub \
  --toc-depth=1 \
  title.txt \
  ./hello-world.md \
  ./values.md \
  ./variables.md \
  ./constants.md \
  ./loops.md \
  ./conditionals.md \
  ./lists.md \
  ./associative-data.md \
  ./quote-and-eval.md \
  ./functions.md
